language: node_js
node_js:
  - 10
cache: npm
env:
  - CODE_TESTS_WORKSPACE=src/test/functional/fixtures CODE_DISABLE_EXTENSIONS=true CODE_TESTS_PATH=${TRAVIS_BUILD_DIR}/out/test/functional PHPENV_VERSION=7.1
before_script:
  - composer global require squizlabs/php_codesniffer:^3.4
  - export PATH=$PATH:$(composer global config bin-dir --absolute)
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
script: npm test
