language: node_js
node_js:
  - 10
php:
  - '7.1'
cache: npm
env:
  - CODE_TESTS_WORKSPACE=src/test/fixtures CODE_DISABLE_EXTENSIONS=true
before_script:
  - composer global require squizlabs/php_codesniffer:^3.4
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
script: npm test
